### ISSUE TITLE
Trimmer causes error: warning: mnemonic TE not found in menu caption Text

### ISSUE THREAD

**Issue by sdurette** [jonlabelle/Trimmer#10]
When loaded this error comes up in the Sublime text command window.

Fix is to change the  Main.sublime-menu.  Line 62 from "mnemonic:"TE",  to "mnemonic":"T",

**Comment by jonlabelle** [comment]
Text mnemonic [fixed](https://github.com/jonlabelle/Trimmer/commit/e4b32cac73f4b775fa096c0ed9ae403f0a129b94).
