### ISSUE TITLE
The 'Delelte empty lines' command can`t delete last empty line

### ISSUE THREAD

**Issue by duanxq1994** [jonlabelle/Trimmer#16]
If I make a newline on the last line, the command cannot delete the newline. 
Or when the last line is blank, the command also does not take effect

I'm not sure if this is a feature, or a bug.

Repair suggestion:
I tried adding a condition '|\s*\Z' to your regex and it seems to work fine

**Comment by jonlabelle** [comment]
Hi @duanxq1994. Thanks for the tip.
