### ISSUE TITLE
After updating new package control Trimmer not working

### ISSUE THREAD

**Issue by gsivaprabu** [jonlabelle/Trimmer#8]
trimmer not shown after press (Ctrl + Shift +P ) in windows7 OS and event not shown in Edit menu also but installed. Not showing any errors, Sorry for my English .

**Comment by jonlabelle** [comment]
@gsivaprabu: Can you try re-installing Trimmer from Package Control?

1. <kbd>ctrl + shift + p</kbd> type **Package Control**: *Remove Package* then **Trimmer**.
2. <kbd>ctrl + shift + p</kbd> type **Package Control**: *Install Package* then **Trimmer**.

If that doesn't working, try again with the [debug option enabled](https://packagecontrol.io/docs/troubleshooting#Enabling_the_Debug_Log), and take a look the console output (<kbd>ctrl + ~</kbd>) for possible errors.

Also, ensure that *Trimmer* is not listed in your `"ignored_packages"` setting.

**Comment by gsivaprabu** [comment]
Dear Jonlabelle,

Thanks for your valuable responsible.

​​​regards,
Sivaprabu Ganesan.
+91-9940-111-413​​

**Comment by gsivaprabu** [comment]
Sorry Johny  trimmer added in ignored list now works fine..

​​
regards,

   [image: --]
Sivaprabu Ganesan
[image: http://]about.me/gsivaprabu
     <http://about.me/gsivaprabu?promo=email_sig>

 <http://about.me/gsivaprabu>
