### ISSUE TITLE
Question on setting up a Trimmer keyboard shortcut

### ISSUE THREAD

**Issue by eatest** [jonlabelle/Trimmer#9]
Hi - wasn't sure where else I could ask a question, so thought I'd try on here. I'd like to add a keyboard shortcut for "Trimmer: Remove blank spaces." on my current selection, but I'm not sure how best to go about this. I found someone else say the syntax is

{ "keys": ["ctrl+1"], "command": "<COMMAND>", "args": {"name": "Packages/User/<SNIPPET NAME>.sublime-snippet"} }

However there is no snippet for Trimmer in Packages/User/ and I was unsure of the command to use. Thanks so much for this plugin and any additional help you can provide!

**Comment by jonlabelle** [comment]
Hi @eatest. You don't need the `args` parameter. 

Try: `{ "keys": ["ctrl+1"], "command": "remove_blank_spaces" }`
